name: gaussian_splatting
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch-cuda=12.1
  - plyfile
  - python=3.10
  - pip
  - pytorch::pytorch
  - pytorch::torchaudio
  - pytorch::torchvision
  - tqdm
  - pip:
    - opencv-python
    - joblib
